name: Linter

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [main]
    types: opened, edited

jobs:
  build:
    name: Python Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # Don't check already existent files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  markdown-lint:
    name: Markdown Linter
    runs-on: ubuntu-latest

    steps:
      - name: malus-markdown-linter
        uses: davidxbors/github-action-markdown-cli@v1.0.4
        with:
          files: .
          config_file: /config/config.json
          rules: /rules/rules.js